apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/keshavswaroop/gitops-eks-cd.git
    targetRevision: master
    path: apps/app

  destination:
    server: https://kubernetes.default.svc
    namespace: cicd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
